import Home from "./home/home.page";
import Dashboard from "./dashboard/dashboard.page";
import Login from "./login/login.page";
import Register from "./register/register.page";
import SharedLayout from "./sharedLayout/sharedLayout.page";
import LandingPage from "./landingPage/LandingPage.page";
import Search from "./search/search.page";
import Upload from "./upload/upload.page";
import Compare from "./compare/compare.page";
import Calendar from "./calendar/calendar.page";
export {Home, Dashboard,Search,Upload, Login, Register, SharedLayout, LandingPage, Compare, Calendar};